---
title: "DLPFC-twelve-sample"
author: "Ziyue Tan"
date: "2023-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
for (i in list.files(pattern = ".R$")) 
  source(i)                      
```

```{r}
sample_list <- c(c(151507: 151510), c(151669:151676))
cluster_numbers <- c(rep(7, 4), rep(5, 4), rep(7, 4))
```


```{r}
sce <- miceadds::load.Rdata2(filename="Human_DLPFC_Visium_processedData_sce_scran_spatialLIBD.rdata")
```

```{r}
set.seed(1)
for (i in 1:12){
  
  sample <- sample_list[i]
  num <- cluster_numbers[i]

  dlpfc <- getRDS("2020_maynard_prefrontal-cortex", sample)
  
  dlpfc <- preprocess(dlpfc, platform = "Visium", n.PCs = 15, n.HVGs = 2000, log.normalize = FALSE)
  
  # BayesSpace
  dlpfc <- SpatialCluster(dlpfc, q = num, d = 15, platform='Visium', n.rep = 100, gamma=3, ncores = 2)

  clusters <- list()
  clusters[["BayesSpace"]] <- dlpfc$spatial.cluster
  
  Y <- reducedDim(dlpfc, "PCA")[, seq_len(15)]

  # K-means
  clusters[["k-means"]] <- kmeans(Y, centers = num)$cluster
  
  # Louvain

  g.jaccard = scran::buildSNNGraph(dlpfc, use.dimred="PCA", type="jaccard")
  clusters[["Louvain"]] <- igraph::cluster_louvain(g.jaccard)$membership
  
  # mclust (BayesSpace initialization)
  library(mclust)
  clusters[["mclust"]] <- Mclust(Y, G = num, modelNames = "EEE", verbose = FALSE)$classification
  
  # stlearn
  # the results have been obtained by stlearn.ipynb,
  # and been stored in "/BayesSpace/DLPFC-stLearn"
  stlearn.path <- gsub("sample", sample, "/Users/tanziyue/Desktop/BayesSpace/DLPFC-stLearn/sample.stLearn_filtered_markers.csv")
  clusters[["stLearn_HVGs"]] <- read.csv(stlearn.path)$X_pca_kmeans + 1
  
  # giotto/HMRF
  # the results have been obtained by DLPFC-Giotto.Rmd, 
  # and been stored in "/BayesSpace/DLPFC-Giotto"
  giotto.path <- gsub("sample", sample, "/Users/tanziyue/Desktop/BayesSpace/DLPFC-Giotto/sample/sample.Giotto_HMRF.csv")
  giotto.col <- gsub("num", num, "HMRF_knum_b.18")
  clusters[["Giotto"]] <-  read.csv(giotto.path)[ , giotto.col]
  
  sce.sample<- sce[, sce$sample_name == sample]
  #Walktrap
  clusters[["Walktrap_HVGs"]] <- sce.sample$HVG_PCA_spatial
  
  # ground truth (manual annotations)
  clusters[["Manual annotation"]] <- sce.sample$layer_guess_reordered
  ARI <- purrr::map(clusters, function(x) mclust::adjustedRandIndex(x, clusters[["Manual annotation"]]))      
            
  if(i == 1){
    ARI.frame <- data.frame("ARI" = unlist(ARI), "algorithm" = names(ARI))
  }else{
    ARI.frame <- rbind(ARI.frame , data.frame("ARI" = unlist(ARI), "algorithm" = names(ARI)))
  }
}
```



```{r}
ARI.frame$algorithm <- factor(ARI.frame$algorithm,levels = c("Walktrap_HVGs","k-means", "mclust", "Louvain", "stLearn_HVGs", "Giotto", "BayesSpace", "Manual annotation"))
ARI.frame <- ARI.frame[-which(ARI.frame$algorithm == "Manual annotation"), ]
ggplot(ARI.frame, aes(x = algorithm, y = ARI)) + geom_boxplot()  + geom_dotplot(binaxis = 'y', stackdir = 'center', dotsize = 0.5) + theme_bw() + labs(title = "Twelve-sample clustering accuracy comparison")
```

```{r}
ARI.frame
```

