---
title: "Simulation-subspots"
author: "Ziyue Tan"
date: "2023-05-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load funtions

for (i in list.files(pattern = ".R$")) {
  source(i)                      
}

```

```{r}
simu.spots  <- function(i, Sigma, v, mu, w, z){
  rmvt(1, sigma = 1 / w[i] * Sigma, df = v, delta = mu[z[i], ])
}
```


## melanoma 
```{r}
set.seed(1)
melanoma <- getRDS(dataset="2018_thrane_melanoma", sample="ST_mel1_rep2")
melanoma <- preprocess(melanoma, platform = "ST", n.PCs = 7, n.HVGs = 2000, log.normalize = FALSE)
melanoma <- SpatialCluster(melanoma, q = 4, d = 7, platform = "ST", gamma = 2, n.rep = 10, ncores = 1)
enhanced.melanoma <- EnhancedCluster(melanoma, q = 4,  d = 7, platform ="ST", mu0 = NULL, Lambda0 = NULL, gamma = 2, alpha = 1, beta = 0.01, n.rep = 10, jitter_scale = 20, jitter_prior = 10, ncores = 1, save_para = TRUE)
```

```{r}
n <- ncol(melanoma)
n.sub <- ncol(enhanced.melanoma)
Y.sub <- reducedDim(enhanced.melanoma, "PCA")

subplots <- 9
vector.sub <- 0 + c(0 : (subplots - 1)) * n
Y.opt <- t((sapply(seq_len(n), 
                   function(x) colMeans(Y.sub[c(x + vector.sub), ]))))

gene <- rowData(melanoma)
loc <- colData(melanoma)[c("row", "col")]

melanoma.opt <- SingleCellExperiment(rowData = gene, colData = loc, reducedDims = list("PCA" = Y.opt))
melanoma.opt  <- preprocess(melanoma.opt, platform = "ST", n.PCs = 7, n.HVGs = 2000, log.normalize = FALSE, skip.PCA = TRUE)
melanoma.opt <- SpatialCluster(melanoma.opt, q = 4, d = 7, platform ="ST", n.rep = 10, gamma = 2, ncores = 1)

cluster.opt <- rep(melanoma.opt$spatial.cluster, subplots)

# optimal ARI
ARI.opt.melanoma <- mclust::adjustedRandIndex(enhanced.melanoma$spatial.cluster, cluster.opt)
```

```{r}
mu <- metadata(enhanced.melanoma)$para$mu
w <- metadata(enhanced.melanoma)$para$w
Lambda <- metadata(enhanced.melanoma)$para$Lambda
z.sub <- enhanced.melanoma$spatial.cluster

Sigma <- solve(Lambda)
v <- 4
```

```{r}

ARI.melanoma <- numeric(20)
sub.loc <- colData(enhanced.melanoma)[, c("sub.row", "sub.col")]
sub.neighbors <-  find.neighbors.sub(sub.loc, "ST")

for(i in 1 : 20){
  
   Y.simu <- t(sapply(1 : n.sub, function(x) as.vector(simu.spots(i = x, Sigma =  Sigma, v = v, mu = mu, w = w, z = z.sub))))
   
  #BayesSpace
  z.simu <-  cluster.results(Y.simu, q = 4, sub.neighbors, 
                             init = enhanced.melanoma$spatial.cluster, 
                             mu0 = colMeans(Y.simu),  Lambda0 = diag(ncol(Y.simu)) * 0.01, 
                             gamma = 2,  alpha = 1, beta = 0.01, ncores = 1,  
                             n.rep =100, save_para = FALSE)
  
  ARI.melanoma[i] <-  mclust::adjustedRandIndex(enhanced.melanoma$spatial.cluster, z.simu)
 
}

```



## OC
```{r}
set.seed(1)
OC <- getRDS("2020_10X-demo_ovarian-cancer", "whole_transcriptome")
OC <- preprocess(OC, platform = "Visium", n.PCs = 15, n.HVGs = 2000, log.normalize = FALSE)

OC <- SpatialCluster(OC, q = 6, d = 15, platform = "Visium", gamma = 3, n.rep = 10, ncores = 2, save_para = TRUE)

enhanced.OC  <- EnhancedCluster(OC, q = 6,  d = 15, platform ="Visium", mu0 = NULL, Lambda0 = NULL, gamma = 3, alpha = 1, beta = 0.01, n.rep = 10, jitter_scale = 20, jitter_prior = 10, ncores = 2, save_para = TRUE)
```

```{r}

n <- ncol(OC)
n.sub <- ncol(enhanced.OC)
Y.sub <- reducedDim(enhanced.OC, "PCA")

subplots <- 6
vector.sub <- 0 + c(0 : (subplots - 1)) * n
Y.opt <- t((sapply(seq_len(n), 
                   function(x) colMeans(Y.sub[c(x + vector.sub), ]))))



gene <- rowData(OC)
loc <- colData(OC)[c("row", "col")]

OC.opt <- SingleCellExperiment(rowData = gene, colData = loc, reducedDims = list("PCA" = Y.opt))

OC.opt  <- preprocess(OC.opt, platform = "Visium", n.PCs = 15, n.HVGs = 2000, log.normalize = FALSE, skip.PCA = TRUE)

OC.opt <- SpatialCluster(OC.opt, q = 6, d = 15, platform = "Visium", n.rep = 5, gamma = 3, ncores = 1)

cluster.opt <- rep(OC.opt$spatial.cluster, subplots)

# optimal ARI
ARI.opt.OC <- mclust::adjustedRandIndex(enhanced.OC$spatial.cluster, cluster.opt)

```

```{r}
mu <- metadata(enhanced.OC)$para$mu
w <- metadata(enhanced.OC)$para$w
Lambda <- metadata(enhanced.OC)$para$Lambda
z.sub <- enhanced.OC$spatial.cluster

Sigma <- solve(Lambda)
v <- 4
```

```{r}

ARI.OC <- numeric(20)

for(i in 1 : 20){
  
   Y.simu <- t(sapply(1 : n.sub, function(x) as.vector(simu.spots(i = x, Sigma =  Sigma, v = v, mu = mu, w = w, z = z.sub))))

  sub.loc <- colData(enhanced.OC)[, c("sub.row", "sub.col")]
  
  #BayesSpace
  sub.neighbors <-  find.neighbors.sub(sub.loc, "ST")
  
  z.simu <-  cluster.results(Y.simu, q = 4, sub.neighbors, 
                             init = enhanced.OC$spatial.cluster, 
                             mu0 = colMeans(Y.simu),  Lambda0 = diag(ncol(Y.simu)) * 0.01, 
                             gamma = 2,  alpha = 1, beta = 0.01, ncores = 1,  
                             n.rep =100, save_para = FALSE)
  
  ARI.OC[i] <-  mclust::adjustedRandIndex(enhanced.OC$spatial.cluster, z.simu)

}
```

```{r}

ARI.frame <- data.frame("ARI" = ARI.melanoma, "datasets" = rep("melanoma", 20))

opt.frame <- data.frame("opt" = c(ARI.opt.melanoma, ARI.opt.OC), "datasets" = c("melanoma", "OC"))

ARI.frame <- rbind(ARI.frame, data.frame("ARI" = ARI.OC, "datasets" = rep("OC", 20)))
ggplot(ARI.frame, aes(x = datasets, y = ARI)) + geom_boxplot()  + 
  geom_jitter(shape=16, position = position_jitter(0.2)) +theme_bw() +   
  geom_errorbar(data = opt.frame, aes(y = opt, ymax = opt, ymin = opt), colour="red")


```

